# Generated by Django 3.1.7 on 2021-03-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='owner',
        ),
        migrations.AddField(
            model_name='goal',
            name='hello',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
