# Generated by Django 3.1.7 on 2021-03-24 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0002_auto_20210324_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='hello',
        ),
        migrations.AddField(
            model_name='goal',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
    ]
